
package com.javen.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUserService", targetNamespace = "http://service.javen.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.javen.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectNameLogin", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectNameLogin")
    @ResponseWrapper(localName = "selectNameLoginResponse", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectNameLoginResponse")
    public User selectNameLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.javen.service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectAll", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectAll")
    @ResponseWrapper(localName = "selectAllResponse", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectAllResponse")
    public List<User> selectAll();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteById", targetNamespace = "http://service.javen.com/", className = "com.javen.service.DeleteById")
    @ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "http://service.javen.com/", className = "com.javen.service.DeleteByIdResponse")
    public void deleteById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateById", targetNamespace = "http://service.javen.com/", className = "com.javen.service.UpdateById")
    @ResponseWrapper(localName = "updateByIdResponse", targetNamespace = "http://service.javen.com/", className = "com.javen.service.UpdateByIdResponse")
    public void updateById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.javen.service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectById", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectById")
    @ResponseWrapper(localName = "selectByIdResponse", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectByIdResponse")
    public User selectById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "selectLogin", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectLogin")
    @ResponseWrapper(localName = "selectLoginResponse", targetNamespace = "http://service.javen.com/", className = "com.javen.service.SelectLoginResponse")
    public Integer selectLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        com.javen.service.SelectLogin.Arg0 arg0);

}
